server:
  port: 8082

spring:
#  application:
#    name: myapp-nacos
  cloud:
    nacos:
      discovery:
        server-addr: 172.19.4.29:8848
  datasource:                                     # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource      # 数据源的类型，可以更改为其他的数据源配置，比如druid
    driver-class-name: com.mysql.cj.jdbc.Driver      # mysql/MariaDB 的数据库驱动类名称
    url: jdbc:mysql://172.19.4.29:3306/myapp?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 10fd41d727cb3986
    hikari:
      connection-timeout: 30000               # 等待连接池分配连接的最大时间（毫秒），超过这个时长还没有可用的连接，则会抛出SQLException
      minimum-idle: 5                         # 最小连接数
      maximum-pool-size: 20                   # 最大连接数
      auto-commit: true                       # 自动提交
      idle-timeout: 600000                    # 连接超时的最大时长（毫秒），超时则会被释放（retired）
      pool-name: DataSourceHikariCP           # 连接池的名字
      max-lifetime: 18000000                  # 连接池的最大生命时长（毫秒），超时则会被释放（retired）
      connection-test-query: SELECT 1
  redis:
    host: 172.19.4.29
    port: 6379
    database: 0
    password: root

  data:
    mongodb:
      uri: mongodb://root:root@172.19.4.29:27017
      database: myapp

  rabbitmq:
    host: 172.19.4.29
    port: 5672
    username: guest
    password: guest
    virtual-host: myapp


# 打开监控
management:
  endpoint:
    web:
      exposure:
        include: '*' # 打开所有监控端点
