server:
  port: ${port:8099}

spring:
#  application:
#      name: myapp-nacos
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.218.129:8848 # nacos 所在的地址
  datasource:                                     # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource      # 数据源的类型，可以更改为其他的数据源配置，比如druid
    driver-class-name: com.mysql.cj.jdbc.Driver      # mysql/MariaDB 的数据库驱动类名称
    url: jdbc:mysql://127.0.0.1:3306/my-app?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root
    hikari:
      connection-timeout: 30000               # 等待连接池分配连接的最大时间（毫秒），超过这个时长还没有可用的连接，则会抛出SQLException
      minimum-idle: 5                         # 最小连接数
      maximum-pool-size: 20                   # 最大连接数
      auto-commit: true                       # 自动提交
      idle-timeout: 600000                    # 连接超时的最大时长（毫秒），超时则会被释放（retired）
      pool-name: DataSourceHikariCP           # 连接池的名字
      max-lifetime: 18000000                  # 连接池的最大生命时长（毫秒），超时则会被释放（retired）
      connection-test-query: SELECT 1
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

  data:
    mongodb:
      uri: mongodb://admin:abc123456@127.0.0.1:27017
      database: myapp

  rabbitmq:
    host: 192.168.218.129
    port: 5672
    username: admin
    password: admin
    virtual-host: myapp

# 打开监控
management:
  endpoint:
    web:
      exposure:
        include: '*'
